#!/usr/bin/env python3

import argparse


from hmg.hangman import Hangman


def get_cli_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--char", default="-", help="Caracter de relleno")
    return parser


def main():
    args = get_cli_parser().parse_args()
    hmg = Hangman(char_tablero=args.char)
    hmg.start_game()


if __name__ == "__main__":
    main()
