#!/usr/bin/env python3

import argparse


from hmg.hangman import Hangman
from hmg.word_utils import get_word_from_internet


def get_cli_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--char", default="-", help="Caracter de relleno")
    return parser


def main():
    palabra_secreta = get_word_from_internet()
    args = get_cli_parser().parse_args()
    hmg = Hangman(char_tablero=args.char, palabra_secreta=palabra_secreta)
    hmg.start_game()


if __name__ == "__main__":
    main()
